ProyectoFinal/LoVisto/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.pagina_principal),
    path('user/<str:llave>', views.pagina_usuario),
    path('aportaciones', views.pagina_aportaciones),
    path('informacion', views.pagina_informacion),
    path('<str:llave>',views.pagina_unrecurso),
]

ProyectoFinal/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login
from django.contrib.auth.views import LogoutView as logout

urlpatterns = [
    path('LoVisto/', include('LoVisto.urls')),
    path('admin/', admin.site.urls),
    path('login/', login.as_view()),
    path('logout/', logout.as_view()),
]

ProyectoFinal/LoVisto/models.py
from django.db import models

# Create your models here.
class Recursos(models.Model): #TOPIC el tipo de recurso que puede meter el ususario
    RECURSO = [
        ('AEMET', 'Tiempo'),
        ('WIKI', 'Wikipedia'),
        ('YT', 'Youtube'),
        ('RE', 'Reddit'),
        ('OTRO', 'Otros'),
    ]
    recursos = models.CharField(max_length=5, choices=RECURSO)
    def __str__(self):
        return str(self.id) + ": " + self.recursos

#Relacion N:N
class Contenido(models.Model):
    clave = models.CharField(max_length=128) #TITULO
    valor = models.TextField() #url
    usuario = models.TextField()
    votos_positivos = models.IntegerField()
    votos_negativos = models.IntegerField()
    fecha = models.DateTimeField('publicado') #Fecha de la aportacion
    NComentarios = models.IntegerField()  #Numero de comentarios
    info = models.TextField()
    recurso = models.ManyToManyField(Recursos)  #Lo relacionamos con la clase Recursos para que el tipo

    def __str__(self):
        return str(self.id) + ": " + self.clave


class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    usuario = models.TextField()
    valor = models.TextField()  #Comentario
    titulo = models.CharField(max_length=200)
    imagen = models.TextField(default="No url") #Optativo(Extra)
    fecha = models.DateTimeField('publicado')

    def __str__(self):
        return str(self.id) + ": " + self.valor

class Votar(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    usuario = models.TextField()
    valor = models.TextField() #Ponemos voto positivo o negativo

    def __str__(self):
        return str(self.contenido) + ": " + self.usuario

ProyectoFinal/templates/aplicacion/ERROR.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
{%block aportacion%}
No se puede extraer mas informacion de la pagina solicitada
{%endblock%}

ProyectoFinal/templates/aplicacion/NoReconocido.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
<p>Este es el titulo</p><br>
{%block aportacion%}
<div class="noreconocido">
  <p>Recurso no reconocido en nuestra plataforma, hemos podido extraer esta informacion</p>
    <p>Este es el titulo:{{titulo}}</p><br>
    <img src={{imagen}}><br>
  <a href={{contenido.valor}}>Pagina Original</a><br><br>
</div>
{%endblock%}

ProyectoFinal/templates/aplicacion/PaginaAportaciones.html
{% extends 'aplicacion/schema.html' %}
{%block cuerpo%}
    {%if contenido_list%}
    <h1>
        <strong>PAGINA DE APORTACIONES</strong>
    </h1>
    <table style="width:auto" align="center">
           {%for Contenido in contenido_list%}

                <li><a href="{{ Contenido.valor }}">{{Contenido.clave}}</a></li><br><br>

           {%endfor%}
   </table>
    {%else%}
        <br>No tenemos contenidos que mostrar</br>
    {%endif%}
{% endblock %}
{% block lateral %}
{% load static %}
    <img src="https://www.solusoft.es/Info/Imagenes/innovacion/aportaciones-big.jpg" alt="aporta" width=100% align="center" heigth="50"><br>
{% endblock %}

ProyectoFinal/templates/aplicacion/PaginaInformacion.html
{% extends 'aplicacion/schema.html' %}
{%block cuerpo%}
<div class="cuadro">
<p>
    <strong>Informacion sobre la practica<br></strong>
</p>
<p>
  Soy Jose Jorge Martinez Fernández del grado de Sistemas de Telecomunicaciones<br>
    Para dicha aplicacion se ha utilizado Django con version 3.1.7, el código con Python 3.8 <br>
    Con la herramienta PyCharm 2021.1.2 (Community Edition).<br>
    Implementado en un sistema Ubuntu 20.04.2 LTS, para parsear los
    recursos se ha realizado con la biblioteca python BeautifulSoup.
    Realiza la funcionalidad minima y de la optativa el favicon, introducir
    como comentario una url de la foto, dos recursos nuevos optativos y
    la implementacion de un iframe con la pagina de la URJC en la pagina principal.
</p>
<ul>
  <li>Para el css la información la he sacado de páginas como:</li>
</ul>
<ol>
    <li><a href="https://developer.mozilla.org/es/docs/Web/HTML">Info Html</a></li>
    <li><a href="https://www.mclibre.org/consultar/htmlcss/html/html-etiquetas.html">Estilos HTML</a></li>
    <li><a href="https://developer.mozilla.org/es/docs/Web/CSS/font-size"> Info CSS</a></li>
    <li><a href="https://uniwebsidad.com/libros/css-avanzado/capitulo-1/texto"> Estilos CSS</a></li>
</ol>
</div>
{% endblock %}
{% block lateral %}
{% load static %}
    <img src="https://www.fael.es/wp-content/uploads/2019/07/info.png" alt="info" width=50% align="center" heigth="50"><br>
{% endblock %}

ProyectoFinal/templates/aplicacion/PaginaPrincipal.html
{% extends 'aplicacion/schema.html' %}
{%block cuerpo%}
{%if contenido_list_crop%}
    <h1>
        <strong>Página Principal</strong><br>
        <p>Encontraras las 10 ultimas aportaciones.<p>
           {%for content in contenido_list_crop%}
    </h1>
<br><br>
                      <table style="width:auto" align="rigth">
                        <th><a href="{{ content.valor }}">{{content.clave}}</a><th>
                        <tr>
                            <td>La url es:</td>
                            <td>{{ content.valor }}</td>
                        </tr>
                        <tr>
                           <td>votos positivos : </td>
                            <td>{{ content.votos_positivos }}</td>
                        </tr>
                        <tr>
                            <td>votos negativos : </td>
                            <td>{{ content.votos_negativos }}</td>
                        </tr>
                        <tr>
                            <td>fecha de publicacion : </td>
                             <td>{{ content.fecha }}</td>
                        </tr>
                          <tr>
                            <td>Publicado por : </td>
                             <td>{{ content.usuario }}</td>
                        </tr>
                        <tr>
                            <td>numero de comentarios : </td>
                            <td>{{ content.NComentarios }}</td>
                        </tr>
                     </table>
        {%endfor%}
    {%else%}
        <p>No tenemos contenidos que mostrar</p>
    {%endif%}

{% endblock %}
{%block lateral%}
    {%  if request.user.is_authenticated%}
        <br>
        <p>Introduce nuevo contenido<p>
        <form action="" method ="POST">
             {% csrf_token %}
            <table style="width:auto" align="left">
               <tr>
                   <td>Titulo:</td>
                   <td><input type="text" name="clave"></td>
               </tr>
                <tr>
                     <td>Cuerpo:</td>
                     <td><input type="text" name="valor"></td>
                </tr>
            </table>
                <input class="boton_diferente" type="submit" name="action" value="Introducir">
        </form>
  {% else %}
    <br><br>

    <p>Para añadir contenidos Inicia Sesión.</p>
    {%endif%}
{% if request.user.is_authenticated%}
        {%if contenido_list_crop%}
<br><br>
            <strong>Ultimas aportaciones de {{request.user.username}}</strong>
             {%for content in contenido_list_crop%}
<br>
                 {% ifequal content.usuario request.user.username %}
                        <a href="{{content.valor}}">{{content.clave}}</a>
                 {%endifequal%}
            {%endfor%}
             <br>

        {%endif%}
  {%endif%}
<p>Previsualizacion de <a href="https://www.urjc.es/">Pagina URJC</a></p>
            <iframe src="https://www.urjc.es/" height="300" width="80%">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>
<br><br><br><br>
{% endblock %}

ProyectoFinal/templates/aplicacion/PaginaUnRecurso.html
{% extends 'aplicacion/schema.html' %}
{%block cuerpo%}
        <tr>
           <td>
                <table style="width:auto" align="center">
                    <th><a href="{{contenido.valor}}">{{contenido.clave}}</a></th>
                    <tr>
                        <td>La url es:</td>
                        <td>{{ contenido.valor }}</td>
                    </tr>
                    <tr>
                        <td>Publicado por : </td>
                        <td>{{ contenido.usuario }}</td>
                    </tr>

                    <tr>
                        <td>votos positivos : </td>
                        <td>{{ contenido.votos_positivos }}</td>
                    </tr>
                    <tr>
                        <td>votos negativos : </td>
                        <td>{{ contenido.votos_negativos }}</td>
                    </tr>
                    <tr>
                        <td>fecha de publicacion : </td>
                        <td>{{ contenido.fecha }}</td>
                    </tr>
                    <tr>
                        <td>numero de comentarios : </td>
                        <td>{{ contenido.NComentarios }}</td>
                    </tr>
                </table>
           </td>
        </tr>
     {% if request.user.is_authenticated %}
        {% if contenido.votar_set.all %}
            {% for voto in contenido.votar_set.all %}
                     {% ifequal voto.usuario request.user.username %}
                       <br> Ya ha votado {{ voto.valor }}
                        <form action="" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_opciones" type="submit" name="action" value="Borrar votacion"></td>
                        </form>
                        <br><br><br><br>
                    {%else%}
                    <br><br>
                    <table style="width:auto" align="left">
                        <form action="" method ="POST">
                                {% csrf_token %}
                            <tr> <td><input class="boton_opciones" type="submit" name="action" value="ME GUSTA"></td>
                        </form>
                        <form action="" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_opciones" type="submit" name="action" value="NO ME GUSTA"></td>
                           </tr>
                        </form>
                    </table>
                        <br><br><br>
                    {% endifequal %}
             {% endfor %}
        {% else %}
        <br>
        <table style="width:auto" align="center">
                        <form action="" method ="POST">
                                {% csrf_token %}
                            <tr> <td><input class="boton_opciones" type="submit" name="action" value="ME GUSTA"></td>
                        </form>

                        <form action="" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_opciones" type="submit" name="action" value="NO ME GUSTA"></td>
                            </tr>
                        </form>
        </table>

<br><br>
        {% endif %}
    {% endif %}
{%block aportacion%}
<br><br><br>
{%endblock%}
<br><br>
    <p>Comentarios</p>
        {% for comentario in contenido.comentario_set.all%}
            <br>
            <table style="width:auto" align="center">
                        <tr>
                               <td><b>Titulo:<b/></td>
                               <td>{{comentario.titulo}}</td>
                        </tr>
                        <tr>
                            <td><b>Cuerpo:<b/></td>
                               <td> {{comentario.valor }}</td>
                        </tr>
                        <tr>
                            <td><b>Usuario:</b></td>
                               <td> {{comentario.usuario }}</td>
                        </tr>
                        <tr>
                            <td><b>Fecha:</b></td>
                            <td>{{ comentario.fecha }}</td>
                        </tr>
                        {%if comentario.imagen %}
                        <tr>
                            <td><b>Imagen:</b></td>
                            <td> <img src={{comentario.imagen}} width="300"> </td>
                        </tr>
                        {%endif%}
            </table>
        {%endfor%}
 <br><br>
    <p>Votos</p>
        {% for voto in votos_list%}
            <br>
            <table style="width:auto" align="center">
                        <tr>
                               <td><b>usuario:<b/></td>
                               <td>{{voto.usuario }}</td>
                        </tr>
                        <tr>
                            <td><b>Cuerpo:<b/></td>
                               <td> {{voto.valor }}</td>
                        </tr>
            </table>
        {%endfor%}
    <br>

{%endblock%}
{%block lateral%}
{%if request.user.is_authenticated%}
    <p>Introduce nuevo comentario</p>
            <form action="" method ="POST">
                <table style="width:auto" align="left">
                    {% csrf_token %}
                       <tr>
                           <td>Titulo:</td>
                           <td> <input type="text" name="titulo"></td>
                        </tr>
                        <tr>
                           <td> <br>Cuerpo:</td>
                           <td> <input type="text" name="valor"></td>
                        </tr>
                        <tr>
                           <td>Url(img):</td>
                           <td> <input type="text" name="imagen"></td>
                        </tr>
                </table> <br> <br> <br>
                    <br/><input class="boton_opciones"  type="submit" name="action" value="Enviar comentario">
            </form>
{% else%}
    <p>Para poder comentar en una publicacion tienes que haber iniciado sesion</p>
{%endif%}
<br>
    {%ifequal  request.user.username  contenido.usuario  %}
     <p>Edita el contenido de la aportacion(url)</p>
        <form action="" method ="POST">
            <table style="width:auto" align="left">
                    {% csrf_token %}
                <tr>
                   <td> Nueva url: </td>
                    <td><input type="text" name="valor"></td>
                </tr>
            </table>
                <input class="boton_difrente" type="submit" name="action" value="Cambiar contenido">
        </form>
<br>
         <p>Borrar contenido</p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_diferente" type="submit" name="action" value="Borrar contenido">
        </form>
    {%else%}
            <br><br><p>Solo {{ content.usuario }} puede editar esta publicacion si has iniciado sesion</p>
    {%endifequal%}
    <br><br>
     <p>Previsualizacion de <a href={{content.clave}}>Pagina recurso</a></p>
   <iframe src="{{ content.valor }}" height="300" width="80%">
    </iframe>
    <br><br>
{%endblock%}

ProyectoFinal/templates/aplicacion/Paginausuario.html
{% extends 'aplicacion/schema.html' %}
{%block cuerpo%}
{% load static %}
<strong>{{request.user.username}}, Bienvenido a tu Pagina Personal <br>en esta pagina a la cual solo
tu tienes acceso encontraras<br>todas tus publicaciones, todos tus comentarios y todos tus votos.
    <br>Ordenados del más antiguo al más reciente.
{%if contenido_list%}</strong>
<br><br>
<p>Publicaciones de {{request.user.username}}</p>
 {%for Contenido in contenido_list%}
             {% ifequal Contenido.usuario request.user.username %}
 <br>
                <table style="width:auto" align="rigth">
                        <th><a href="{{ Contenido.valor }}">{{Contenido.clave}}</a></th>
                        <tr>
                            <td>La url es:</td>
                            <td>{{ Contenido.valor }}</td>
                        </tr>
                        <tr>
                           <td>votos positivos : </td>
                            <td>{{ Contenido.votos_positivos }}</td>
                        </tr>
                        <tr>
                            <td>votos negativos : </td>
                            <td>{{ Contenido.votos_negativos }}</td>
                        </tr>
                        <tr>
                            <td>fecha de publicacion : </td>
                             <td>{{ Contenido.fecha }}</td>
                        </tr>
                          <tr>
                            <td>Publicado por : </td>
                             <td>{{ Contenido.usuario }}</td>
                        </tr>
                        <tr>
                            <td>numero de comentarios : </td>
                            <td>{{ Contenido.NComentarios }}</td>
                        </tr>
                </table>
               </td>
            </tr>
             {%endifequal%}
        {%endfor%}
<br>
{%else%}
        <p>No tenemos contenidos que mostrar</p>
{%endif%}
<p>Comentarios de {{request.user.username}}</p>
{%if comentario_list %}
        {%for comentario in comentario_list%}
            {% ifequal comentario.usuario request.user.username %}
                <br>
                <table style="width:auto" align="center">
                     <tr>
                         <td><b>Titulo comentario:</b></td>
                         <td>{{comentario.titulo }}</td>
                     </tr>
                     <tr>
                         <td><b>tema comentado:</b></td>
                         <td>{{comentario.contenido.clave }}</td>
                     </tr>
                    <tr>
                        <td><b>Cuerpo:</b></td>
                        <td> {{comentario.valor }}</td>
                    </tr>
                    <tr>
                        <td><b>Fecha:</b></td>
                        <td>{{ comentario.fecha }}</td>
                    </tr>
                    {%if comentario.imagen %}
                    <tr>
                        <td><b>Imagen:</b></td>
                        <td><img src={{comentario.imagen}} width="100"> </td>
                    </tr>
                    {%endif%}
                </table>

             {%endifequal%}
    {%endfor%}
{%endif%}
 <br> <br> <br>
 <br> <br> <br>
{%endblock%}
{%block lateral%}

<p>Votos de {{request.user.username}}</p>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/User_icon_2.svg/2048px-User_icon_2.svg.png" alt="user" width=10% align="left" heigth="10"><br>
<br>
{%if votos_list %}
    {%for voto in votos_list%}
            {% ifequal voto.usuario request.user.username %}
                <table style="width:auto" align="left">
                    <tr>
                        <td><b>Valor del voto :</b></td>
                        <td>{{voto.valor }}</td>
                    </tr>
                    <tr>
                        <td><b>tema votado:</b></td>
                         <td>{{voto.contenido.clave }}</td>
                    </tr>
                </table>
                <br> <br> <br>
            {%endifequal%}
    {%endfor%}
{%endif%}
{% endblock %}

ProyectoFinal/templates/aplicacion/Reddit.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
{%block aportacion%}
<div class="reddit">
<p>Titulo Reddit: {{titulo}}</p>
<p>Texto: {{texto}}</p>
<p><a href="https://www.reddit.com/r/django/comments/n842st">Publicado
en [subreddit]</a>. Aprobación: {{aprob}}.</p>
</div>
{%endblock%}

ProyectoFinal/templates/aplicacion/Wiki.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
{%block aportacion%}
<div class="wikipedia">
  <p>Articulo Wikipedia: {{titulo}}</p>
  <img src={{imagen}}>
  <p>Texto: {{texto}}</p>
  <a href={{contenido.valor}}>Artículo original</a>
</div>
</div>
{%endblock%}

ProyectoFinal/templates/aplicacion/XML.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>XML</title>
</head>
<body>
&lt;?xml version="1.0"?>
    <test>
        {% for contenido in Contenido %}
         <entries>
            <br><br>&lt;Id="{{ contenido.id }}">'
                <br>&lt;Usuario>{{ contenido.usuario }}&lt;/Usuario>
                <br>&lt;Titulo_noticia>{{ contenido.clave }}&lt;/clave>
                <br>&lt;Url_noticia>{{ contenido.valor }}&lt;/valor>
                <br>&lt;Votos positivos>{{ contenido.votos_positivos }}&lt;/Votos positivos>
                <br>&lt;Votos negativos>{{ contenido.votos_negativos }}&lt;/Votos negativos>
                <br>&lt;Fecha>{{ contenido.fecha }}&lt;/Fecha>
                <br>&lt;NComentarios>{{ contenido.NComentarios }}&lt;/NComentarios>
         </entries>
        {% endfor %}
    </test>
</body>
</html>

ProyectoFinal/templates/aplicacion/amet.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
{%block aportacion%}
<div class="aemet">
<p>{{titulo}}</p>
<ul>
    <li>Dia:{{fecha}}.</li>
    <li> Temperatura 12-18h: {{temperatura}}</li>
    <li>Temperatura mínima y máxima (°C):{{maxymin}}</li>
    <li>Probabilidad de precipitación:{{precipitacion}}</li>
    <li>Viento:{{viento}}</li>
    <li>Ultravioleta:{{ultravioleta}}</li>
</ul>
<br>Nota Copyright:{{copy}}
   <br><a href={{contenido.valor}}>Página AEMET</a>
</div>
{%endblock%}

ProyectoFinal/templates/aplicacion/okdiario.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
{%block aportacion%}
<div class="okdiario">
<p>Titulo de Noticia: {{titulo}}</p>
   <p>Imagen:</p>
   <img src={{imagen}}>
<br>Informacion Extraida de:
   <br><a href={{contenido.valor}}>Página Noticia</a>
</div>
{%endblock%}

ProyectoFinal/templates/aplicacion/schema.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/jpg" href="https://as1.ftcdn.net/jpg/02/96/91/42/500_F_296914204_8F0EmCJh8nVo7c0MYJtwUdEqnG1xs6Bq.jpg">

    {%if oscuro%}
        <link rel="stylesheet" href="{% static 'Oscuro.css' %}">
    {%else%}
         <link rel="stylesheet" href="{% static 'Normal.css' %}">
    {%endif%}

<title>LoVisto2021</title>


</head>
    <body>
        <div class="header">
            {% block header %}
            <font size="10" face="Comic Sans MS,arial,verdana">¡Bienvenidos a la Aplicacion LoVisto!</font>
            {% load static %}
            <img src="https://www.elearningmedia.es/sites/default/files/2019-07/URJC.png" alt="logo URJC" width=10% align="left" heigth="100">
            <img src="https://i.pinimg.com/originals/5e/3a/25/5e3a254e90714d364b4cd042ec9c7a43.gif" alt="bola mundo" width=10% align="right" heigth="100">
            {%if request.user.is_authenticated%}
            <table2>
            <P align="left">Usuario:{{request.user.username}}</P>
            <form action="" method ="POST" >
                    {% csrf_token %}
                    <div id="session-left">
                    <input class="boton_opciones" type="submit" name="action" value="Cerrar sesion">
                    </div>
            </form>
            </table2>
            {% else %}
                <br>No estas autenticado.<br>
                <form action="" method ="POST">
                    {% csrf_token %}
                     <input class="boton_opciones" type="submit" name="action" value="Iniciar sesion">
                </form>
            {% endif %}
            {% endblock %}
        </div>
        <div class="opciones">
             {%block opciones%}
            {%if request.user.is_authenticated%}
                <form action="" method ="POST">
                         {% csrf_token %}
                        <input class="boton_opciones" type="submit" name="action" value="Pagina del Usuario">
                </form>
                <form action="" method ="POST">
                        {% csrf_token %}
                         <input class="boton_opciones" type="submit" name="action" value="Pagina Principal">
                </form>
                <form action="" method ="POST">
                        {% csrf_token %}
                         <input class="boton_opciones" type="submit" name="action" value="Pagina Aportaciones">
                </form>
                <form action="" method ="POST">
                        {% csrf_token %}
                         <input class="boton_opciones" type="submit" name="action" value="Informacion">
                </form>

                <form action="" method ="POST">
                    {% csrf_token %}
                        <input class="boton_opciones" type="submit" name="action" value="OSCURO">
                </form>

                <form action="" method ="POST">
                    {% csrf_token %}
                        <input class="boton_opciones" type="submit" name="action" value="CLARO">
                </form>

                <td><a href="/LoVisto/index?format=xml/" class="nav-link px-2 text-white">XML</a></td>
                <td><a href="/LoVisto/index?format=json/" class="nav-link px-2 text-white">JSON</a></td>
            {% else %}
                <form action="" method ="POST">
                        {% csrf_token %}
                         <input class="boton_opciones" type="submit" name="action" value="Pagina Principal">
                </form>
                <form action="" method ="POST">
                        {% csrf_token %}
                         <input class="boton_opciones" type="submit" name="action" value="Pagina Aportaciones">
                </form>
                <form action="" method ="POST">
                        {% csrf_token %}
                         <input class="boton_opciones" type="submit" name="action" value="Informacion">
                </form>
            {% endif %}
         {%endblock%}
        </div>

        <cuerpo>
            {% block cuerpo %}
            {% endblock %}
        </cuerpo>
        <aside>
            {% block lateral %}

            {% endblock %}
        </aside>

        <div class="final">
            {% block final %}
              <br>
            <br>jj.martinezf.2017@alumnos.urjc.es
            <br>
            Este sitio enlaza a
            {% for contenido in lista_piedepagina %}
            <a href="{{contenido.valor}}">{{contenido.clave}}</a>,
            {% endfor %}
            y otros muchos sitios.
            {% endblock %}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

ProyectoFinal/templates/aplicacion/vuelos.html
{% extends 'aplicacion/PaginaUnRecurso.html' %}
{%block aportacion%}
<div class="vuelos">
<p>Titulo de Pagina: {{titulo}}</p>
   <p>Introduccion: {{texto}}</p>
   <p>IDA: {{texto1}}</p>
<br>Informacion Extraida de:
   <br><a href={{contenido.valor}}>KAYAK</a>
</div>
{%endblock%}